#!/bin/bash

# .git/hooks/commit-msg
# Copy ticket id from current branch to commit message if that match pattern

message=`grep -v "^\s*[;#]" $1`

pattern="^\([A-Z]\+-[0-9]\+\)/.*$"
branch=$( git symbolic-ref HEAD | sed "s%refs/heads/%%g" )
ticket=$( echo $branch | sed -e "s%$pattern%\1%" )

if [ ! "$message" ]
then
    # echo "Empty message not allowed"
    exit 1
fi

if [ ! "`echo $branch | grep $pattern`" ]
then
    # echo "Branch name doesnt match pattern"
    exit 0
fi


if [ "`echo $message | grep $ticket`" ]
then
    # echo "Ticket already in comment"
    exit 0
fi

echo -e "\n$ticket" >> $1
