#!/bin/sh

# .git/hooks/commit-msg
# Copy ticket id from current branch to commit message if that match pattern

pattern='^\([A-Z]\+-[0-9]\+\)/.*$'

branch=$(git symbolic-ref HEAD | sed 's/refs\\/heads\\///g')

if [ ! $( echo $branch | grep $pattern ) ]
then
    exit 0
fi

ticket=$( echo $branch | sed -e "s%$pattern%\1%" )

echo -e "\n$ticket" >> $1
